name: digitalboda-backend
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm digitalboda_backend.wsgi
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /admin/
  routes:
  - path: /
  envs:
  - key: DEBUG
    value: "False"
  - key: DJANGO_ENV
    value: "production"
  - key: PORT
    value: "8080"

databases:
- name: digitalboda-db
  engine: PG
  num_nodes: 1
  size: basic-xs
  version: "15"

jobs:
- name: migrate
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  run_command: python manage.py migrate
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY