# Generated by Django 5.2.6 on 2025-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rider_enumerator_id_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
