# Generated by Django 5.2.6 on 2025-09-11 08:34

import django.db.models.deletion
import riders.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_rider_fcm_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='id_access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='id_last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='id_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='id_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='id_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ids', to='riders.enumerator'),
        ),
        migrations.AddField(
            model_name='rider',
            name='national_id_encrypted',
            field=riders.encryption.EncryptedIDField(blank=True, help_text='Encrypted ID number', null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='national_id_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='IDAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_ID', 'Viewed ID'), ('SET_ID', 'Set ID'), ('VERIFY_ID', 'Verified ID'), ('UPDATE_ID', 'Updated ID'), ('EXPORT_ID', 'Exported ID'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt')], max_length=30)),
                ('reason', models.CharField(blank=True, help_text='Reason for accessing ID', max_length=200)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_access_logs', to='riders.rider')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rider', '-timestamp'], name='riders_idac_rider_i_b34824_idx'), models.Index(fields=['accessed_by', '-timestamp'], name='riders_idac_accesse_97815c_idx'), models.Index(fields=['action', '-timestamp'], name='riders_idac_action_5684a6_idx')],
            },
        ),
    ]
