# Generated by Django 5.2.6 on 2025-09-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_add_encrypted_id_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='face_match_score',
            field=models.FloatField(blank=True, help_text='Face matching confidence score', null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='photo_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Photos Verified'), ('REJECTED', 'Photos Rejected'), ('FLAGGED', 'Flagged for Review')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='photo_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='photo_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_photos', to='riders.enumerator'),
        ),
        migrations.CreateModel(
            name='PhotoVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('PROFILE', 'Profile Photo'), ('ID_DOCUMENT', 'ID Document')], max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review')], default='PENDING', max_length=20)),
                ('is_authentic', models.BooleanField(help_text='Overall authenticity determination', null=True)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1)', null=True)),
                ('face_match_score', models.FloatField(help_text='Face matching confidence (0-1)', null=True)),
                ('verification_details', models.JSONField(default=dict, help_text='Detailed verification results')),
                ('warnings', models.JSONField(default=list, help_text='Verification warnings')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Additional notes from reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_verifications', to='riders.rider')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', 'verification_status'], name='riders_phot_rider_i_7cafb9_idx'), models.Index(fields=['verification_status', '-created_at'], name='riders_phot_verific_645c88_idx')],
                'unique_together': {('rider', 'photo_type')},
            },
        ),
    ]
