# Generated by Django 5.2.6 on 2025-09-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0006_add_photo_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='national_id_encrypted',
        ),
    ]
