# Generated by Django 5.2.6 on 2025-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_remove_rider_national_id_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumerator',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
