# Generated by Django 5.2.6 on 2025-09-14 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0008_enumerator_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLiteracyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('session_count', models.IntegerField()),
                ('total_duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points_value', models.IntegerField()),
                ('icon', models.CharField(default='📱', max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('check_in_gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('trainer_notes', models.TextField(blank=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance', to='riders.rider')),
            ],
            options={
                'ordering': ['-registration_time'],
            },
        ),
        migrations.CreateModel(
            name='PostSessionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trainer_feedback', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=20, null=True)),
                ('trainer_notes', models.TextField(blank=True)),
                ('self_assessment_rating', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='riders.sessionattendance')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSkillsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('source', models.CharField(choices=[('ATTENDANCE', 'Session Attendance'), ('ASSESSMENT', 'Post-Session Assessment'), ('PERFECT_ATTENDANCE', 'Perfect Module Attendance'), ('EARLY_REGISTRATION', 'Early Registration'), ('PEER_REFERRAL', 'Peer Referral'), ('TRAINER_BONUS', 'Trainer Recognition Bonus'), ('SKILL_MILESTONE', 'Digital Skill Milestone')], max_length=20)),
                ('bonus_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_points', to='riders.rider')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riders.sessionattendance')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_verified', models.BooleanField(default=False)),
                ('rider_verification_time', models.DateTimeField(blank=True, null=True)),
                ('trainer_verified', models.BooleanField(default=False)),
                ('trainer_verification_time', models.DateTimeField(blank=True, null=True)),
                ('trainer_id_entered', models.CharField(max_length=50)),
                ('distance_from_venue_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='riders.sessionattendance')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('location_name', models.CharField(max_length=200)),
                ('location_address', models.TextField()),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('capacity', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='riders.enumerator')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='riders.sessionschedule'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('learning_objectives', models.JSONField(default=list)),
                ('required_materials', models.JSONField(default=list)),
                ('points_value', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='riders.digitalliteracymodule')),
            ],
            options={
                'ordering': ['module', 'session_number'],
                'unique_together': {('module', 'session_number')},
            },
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='riders.trainingsession'),
        ),
        migrations.CreateModel(
            name='DigitalLiteracyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_attended', models.IntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_session_attended', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.digitalliteracymodule')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_literacy_progress', to='riders.rider')),
            ],
            options={
                'unique_together': {('rider', 'module')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('schedule', 'rider')},
        ),
    ]
