# Generated by Django 5.2.6 on 2025-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0009_digitalliteracymodule_sessionattendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalliteracymodule',
            name='session_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalliteracymodule',
            name='total_duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
