# Generated by Django 5.2.6 on 2025-09-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0010_alter_digitalliteracymodule_session_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(help_text='Unique stage identifier (e.g., STAGE001)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Stage name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Stage description or additional info')),
                ('address', models.CharField(help_text='Physical address of the stage', max_length=200)),
                ('district', models.CharField(help_text='District where stage is located', max_length=50)),
                ('division', models.CharField(blank=True, help_text='Division/sub-county', max_length=50)),
                ('parish', models.CharField(blank=True, help_text='Parish/ward', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('gps_radius', models.IntegerField(default=100, help_text='Allowed GPS radius in meters for verification')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=15)),
                ('capacity', models.IntegerField(default=50, help_text='Maximum number of riders at this stage')),
                ('training_capacity', models.IntegerField(default=25, help_text='Maximum participants per training session')),
                ('stage_chairman', models.CharField(blank=True, help_text='Stage chairman name', max_length=100)),
                ('chairman_phone', models.CharField(blank=True, help_text='Chairman contact', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boda Boda Stage',
                'verbose_name_plural': 'Boda Boda Stages',
                'ordering': ['stage_id'],
            },
        ),
        migrations.CreateModel(
            name='StageRiderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True, help_text="Is this the rider's primary stage?")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='riders.rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_assignments', to='riders.stage')),
            ],
            options={
                'ordering': ['-is_primary', '-assigned_date'],
                'unique_together': {('rider', 'stage')},
            },
        ),
    ]
