# Generated by Django 5.2.6 on 2025-09-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0011_stage_stageriderassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('attendance_window', 'Attendance Window Open'), ('session_starting', 'Session Starting Soon'), ('achievement_unlocked', 'Achievement Unlocked'), ('new_module', 'New Module Available'), ('weekly_progress', 'Weekly Progress Report')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField(help_text='When to send this notification')),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riders.digitalliteracymodule')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='riders.rider')),
                ('session_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riders.sessionschedule')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_time', 'status'], name='riders_noti_schedul_73cf39_idx'), models.Index(fields=['rider', 'notification_type'], name='riders_noti_rider_i_250b93_idx')],
            },
        ),
    ]
